name: Autopuller Tests
on: push
jobs:
  backend-tests:
    runs-on: ubuntu-latest 
    env:
      REMOTE: GITHUB
      PYTHONDONTWRITEBYTECODE: 1  
      PYTHONFLAGS: -B
      GITHUBKEY: ${{secrets.GITHUBKEY}}  

    steps:
      - uses: actions/checkout@v2
        

      - name: List the env variables
        run: echo $DOCKERIZED && echo $PRODUCTION

      - name: Check the secret
        run: echo $GITHUBKEY | head -c 3
        
