name: Autopuller Tests
on: push
jobs:
  backend-tests:
    runs-on: ubuntu-latest 
    env:
      REMOTE: GITHUB
      PYTHONDONTWRITEBYTECODE: 1  
      PYTHONFLAGS: -B
      PYTHONPATH: .

      GITHUBKEY: ${{secrets.GITHUBKEY}}
      REPONAME:  https://www.github.com/amunchet/autopuller/


    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        

      - name: List the env variables
        run: echo $DOCKERIZED && echo $PRODUCTION

      - name: Check the secret
        run: echo $GITHUBKEY | head -c 3
        
      - name: Install requirements.txt
        run: pip3 install -r requirements.txt

      - name: Run tests
        run: pytest --cov=. --cov-fail-under=95 --cov-report term-missing -x

  backend-lint:
    needs: backend-tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install black


    - name: Fix linting errors
      run: |
        black .

    - name: Commit linted files
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Automatic linting" || true

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
