name: Autopuller Tests
on: push
jobs:
  backend-tests:
    runs-on: ubuntu-latest 
    env:
      REMOTE: GITHUB
      PYTHONDONTWRITEBYTECODE: 1  
      PYTHONFLAGS: -B  

    steps:
      - uses: actions/checkout@v2
        
      - name: List the env variables
        run: echo $DOCKERIZED && echo $PRODUCTION
        
