name: Autopuller Tests
on: push
jobs:
  backend-tests:
    runs-on: ubuntu-latest 
    env:
      REMOTE: GITHUB
      PYTHONDONTWRITEBYTECODE: 1  
      PYTHONFLAGS: -B
      PYTHONPATH: .

      GITHUBKEY: ${{secrets.GITHUBKEY}}
      REPONAME:  /amunchet/autopuller/


    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        

      - name: List the env variables
        run: echo $DOCKERIZED && echo $PRODUCTION

      - name: Check the secret
        run: echo $GITHUBKEY | head -c 3
        
      - name: Install requirements.txt
        run: pip3 install -r requirements.txt

      - name: Run tests
        run: pytest --cov=. --cov-fail-under=95 --cov-report term-missing -x

